spring:
  application:
    name: ms-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.application.name:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'
  environment: development